@uri=http://localhost:4416

### index
GET {{uri}}

### hello
GET {{uri}}/hello/John

### Json POST
POST {{uri}}/json-post
Content-Type: multipart/form-data; boundary=FormDataBoundary7MA4YWxkTrZu0gW

--FormDataBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="person"

{
    "name": "john",
    "age": 9999
}

--FormDataBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="panic.png"
Content-Type: image/jpg

< ./panic.png

--FormDataBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="panic1.png"
Content-Type: image/jpg

< ./panic1.png

--FormDataBoundary7MA4YWxkTrZu0gW--


### user+
GET {{uri}}/user/1/2?name=haha&age=123


### user+
GET {{uri}}/user/1


### html
GET {{uri}}/hello.html